<?php
/**
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 */
?>

<?php $storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt(); ?>
<span data-action="toggle-nav" class="action nav-toggle">
    <span><?= __('Toggle Nav') ?></span>
</span>

<div class="promoCode hidden-xs">
    <div class="promoInner">
        <?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('promotion_info')->toHtml();?>
    </div>
</div>

<?php if ($block->isHomePage()): ?>
<strong class="logo">
<?php else: ?>
    <a class="logo" href="<?= $block->getUrl(''); ?>" title="<?= $storeName ?>">
<?php endif ?>

    <img src="<?= $block->getLogoSrc() ?>" alt="<?= $block->getLogoAlt() ?>"
        <?= $block->getLogoWidth() ? 'width="' . $block->getLogoWidth() . '"' : '' ?>
        <?= $block->getLogoHeight() ? 'height="' . $block->getLogoHeight() . '"' : '' ?>
    />

<?php if ($block->isHomePage()): ?>
</strong>
<?php else: ?>
    </a>
<?php endif ?>

<div class="promoCode visible-xs">
    <div class="promoInner">
        <?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('promotion_info')->toHtml();?>
    </div>
</div>