<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View*/
?>
<?php
$_product = $block->getProduct();
$_wishlistSubmitParams = $this->helper('Magento\Wishlist\Helper\Data')->getAddParams($_product);
$compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');

$_objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $_objectManager->get('Magento\Store\Model\StoreManagerInterface');
$currentStore = $storeManager->getStore();
$baseUrl = $currentStore->getBaseUrl();
$mediaUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
$linkUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_LINK);
// towishlist
?>

<div class="product-addto-links" data-role="add-to-links">
    <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()) : ?>
        <a href="#" class="action " data-post='<?= $_wishlistSubmitParams; ?>' data-action="add-to-wishlist">
            <img class="heartIcon" src="<?= $mediaUrl?>/images/icon/heart.png" />
            <span class="hidden-xs">Add to Wish List</span>
        </a>
    <?php endif; ?>
    <a href="#" data-post='<?= $compareHelper->getPostDataParams($_product);?>'
        data-role="add-to-links" class="hidden action tocompare">
        <span><?= __('Add to Compare') ?></span>
    </a>
</div>
<script type="text/x-magento-init">
    {
        "body": {
            "addToWishlist": <?= $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($block->getWishlistOptions())?>
        }
    }
</script>
