<?php
$product = $block->getProduct();
?>

<div class="detailInfoWrapper">
    <div class="detailInner">
        <div class="detailHead"><span>Detail</span><div class="dropContent"></div></div>
        <div class="content hidden">
            <?= $product->getDescription() ?>
        </div>
    </div>
    <div class="detailInner">
        <div class="detailHead">
            <span>Editor's Review</span><div class="dropContent"></div>
        </div>
        <div class="content hidden">
            <?= $product->getReviewText() ?>
        </div>
    </div>
</div>


<script type="text/javascript">
    require(['jquery', 'jquery/ui'], function($){
        $(document).ready(function($) {
            $(window).load(function() {
                $('.detailHead').click(function(){
                    if ($(this).find('.dropContent').hasClass('active')) {
                        $(this).parent().find('.content').addClass("hidden");
                        $(this).find('.dropContent').removeClass("active");
                    } else {
                        $(this).parent().parent().find('.content').addClass("hidden");
                        $(this).parent().parent().find('.dropContent').removeClass("active");
                        $(this).parent().find('.content').removeClass("hidden");
                        $(this).find('.dropContent').addClass("active");
                    }
                })
            });
        });
    });
</script>


