<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
?>

<?php
$_objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$formKey = $_objectManager->get('Magento\Checkout\Block\Onepage')->getFormKey();
$storeManager = $_objectManager->get('Magento\Store\Model\StoreManagerInterface');
$currentStore = $storeManager->getStore();
$mediaUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
?>

<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?= __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
//    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
//    } 
//    
//    else {
//        $viewMode = 'list';
//        $image = 'category_page_list';
//        $showDescription = true;
//        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
//    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?= $viewMode; ?> products-<?= $viewMode; ?>">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <?=($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                <div class="product-item-info" data-container="product-grid">
                    <?php
                    $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>
                    <?php $label = $_product->getIsSale() ? "isSalePr ":"";
                        $label .= $_product->getIsNew() ? "isNewPr":"";
                    ?>

                    <!--  Hover - Quick View -->
                    <?php $addCart = $block->getAddToCartPostParams($_product); ?>

                    <div class="hoverProductWrapper img-resp img150 <?= $label ?>">
                        <div class="hoverProduct">
                            <div class="parentTable">
                                <div class="cellTable">
                                    <a href="javascript:void(0);" class="list-quickView"
                                          data-title="<?= $_helper->productAttribute($_product, $_product->getName(), 'name') ?>"
                                          data-url="<?= $_product->getProductUrl() ?>"
                                          data-sku="<?= $_product->getSku() ?>"
                                          data-img="<?= $mediaUrl . 'catalog/product'. $_product->getImage() ?>"
                                          data-price="<?= number_format((float)$_product->getFinalPrice(), 2, '.', '')  ?>"
                                          data-des="<?= $_product->getDescription()?>"
                                          data-action="<?= $addCart['action'] ?>"
                                          data-product="<?= $addCart['data']['product'] ?>"
                                          data-name="<?=  Action::PARAM_NAME_URL_ENCODED ?>"
                                          data-name-val="<?= $addCart['data'][Action::PARAM_NAME_URL_ENCODED];  ?>"
                                          data-form-key='<?= $formKey ?>'
                                    >
                                        <div class="quickView"><span>Quick View</span></div>
                                    </a>
                                    <a href="<?= $_product->getProductUrl() ?>">
                                        <div class="viewProduct">View Product Detail</div>
                                    </a>
                                </div>

                            </div>
                        </div>
                        <img src="<?= $productImage->getImageUrl() ?>" />
                    </div>


                    <div class="product details product-item-details">
                        <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?= $_product->getProductUrl() ?>">
                                <?= $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                            </a>
                        </strong>
                        <?= $block->getReviewsSummaryHtml($_product, $templateType); ?>
                        <?= $block->getProductPrice($_product) ?>
                        <?= $block->getProductDetailsHtml($_product); ?>

                        <div class="product-item-inner">
                            <div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                                <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                    <?php if ($_product->isSaleable()): ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form" action="<?= $postParams['action']; ?>" method="post">
                                            <input type="hidden" name="product" value="<?= $postParams['data']['product']; ?>">
                                            <input type="hidden" name="<?= Action::PARAM_NAME_URL_ENCODED; ?>" value="<?= $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                            <?= $block->getBlockHtml('formkey')?>
                                            <button type="submit"
                                                    title="<?= $block->escapeHtml(__('Add to Cart')); ?>"
                                                    class="action tocart primary">
                                                <span><?= __('Add to Cart') ?></span>
                                            </button>
                                        </form>
                                    <?php else: ?>
                                        <?php if ($_product->getIsSalable()): ?>
                                            <div class="stock available"><span><?= __('In stock') ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?= __('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                                <div data-role="add-to-links" class="actions-secondary"<?= strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
                                    <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                        <a href="#"
                                           class="action towishlist"
                                           title="<?= $block->escapeHtml(__('Add to Wish List')); ?>"
                                           aria-label="<?= $block->escapeHtml(__('Add to Wish List')); ?>"
                                           data-post='<?= $block->getAddToWishlistParams($_product); ?>'
                                           data-action="add-to-wishlist"
                                           role="button">
                                            <span><?= __('Add to Wish List') ?></span>
                                        </a>
                                    <?php endif; ?>
                                    <?php
                                    $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                                    ?>
                                    <a href="#"
                                       class="action tocompare"
                                       title="<?= $block->escapeHtml(__('Add to Compare')); ?>"
                                       aria-label="<?= $block->escapeHtml(__('Add to Compare')); ?>"
                                       data-post='<?= $compareHelper->getPostDataParams($_product); ?>'
                                       role="button">
                                        <span><?= __('Add to Compare') ?></span>
                                    </a>
                                </div>
                            </div>
                            <?php if ($showDescription):?>
                                <div class="product description product-item-description">
                                    <?= $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                    <a href="<?= $_product->getProductUrl() ?>" title="<?= $_productNameStripped ?>"
                                       class="action more"><?= __('Learn More') ?></a>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
                <?=($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
    </div>
    <?= $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>

    <script type="text/javascript">
        require(['jquery', 'jquery/ui'], function ($) {
            $(document).ready(function () {
                // Click Quick View
                $('.list-quickView').click(function(){
                    var title = $(this).attr("data-title"),
                        url = $(this).attr("data-url"),
                        img = $(this).attr("data-img"),
                        sku = $(this).attr("data-sku"),
                        price = $(this).attr("data-price"),
                        des = $(this).attr("data-des");

                    var action = $(this).attr("data-action"),
                        productId = $(this).attr("data-product"),
                        name = $(this).attr("data-name"),
                        nameVal = $(this).attr("data-name-val"),
                        formKey = $(this).attr("data-form-key");

                    $('#imgQuickView').attr("src",img);
                    $('#titQuickView').attr("href",url);
                    $('#titQuickView').text(title);
                    $('#skuQuickView').text("Model: "+sku);
                    $('#priceQuickView').text('$ '+price);
                    $('#desQuickView').html(des);

                    $('#addToCartQuickView > form').attr("action",action);
                    $('#addToCartQuickView input.productWV').val(productId);
                    $('#addToCartQuickView input.uenc').attr("name",name);
                    $('#addToCartQuickView input.uenc').val(nameVal);
                    $('#addToCartQuickView input.formKeyWV').val(formKey);
                    $('#viewDetailId').attr("href",url);

                    $('.containerPopUpWrap').addClass("open");
                });
                // Click close pop-up quickView
                $('#closeQuickViewAction').click(function() {
                    $('.containerPopUpWrap').removeClass("open");
                })
            });
        });
    </script>
<?php endif; ?>
