<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $block \Magento\Swatches\Block\Product\Renderer\Configurable */ ?>

<div class="swatch-opt"></div>
<div class="summaryDetail"><?= $block->getProduct()->getSummary() ?></div>
<div class="clickSizeChart"><span>* Size Chart</span></div>
<div id="sizeChartContent">
    <div class="wrap">
        <div id="closeSizeChart">( Close )</div>
        <div class="content">
            <?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('size_chart')->toHtml();?>
        </div>
    </div>
</div>
<script>
    require(["jquery", "jquery/ui", "swatchRenderer"], function ($) {
        $('.swatch-opt').SwatchRenderer({
            jsonConfig: <?= $swatchOptions = $block->getJsonConfig(); ?>,
            jsonSwatchConfig: <?= $swatchOptions = $block->getJsonSwatchConfig(); ?>,
            mediaCallback: '<?= $block->getMediaCallback() ?>'
        });
    });
</script>

<div class="lineQuickView"></div>

<script type="text/javascript">
    require(['jquery', 'jquery/ui'], function($){
        $(document).ready(function($) {
            $(window).load(function() {
                jQuery('.clickSizeChart > span').click(function(){
                    if (jQuery('#sizeChartContent').hasClass("open")) {
                        jQuery('#sizeChartContent').removeClass('open');
                    } else {
                        jQuery('#sizeChartContent').addClass('open');
                    }
                });
                jQuery('#closeSizeChart').click(function(){
                    jQuery('#sizeChartContent').removeClass('open');
                })
            });
        });
    });
</script>

