<?php
$_objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $_objectManager->get('Magento\Store\Model\StoreManagerInterface');
$currentStore = $storeManager->getStore();
$baseUrl = $currentStore->getBaseUrl();
$mediaUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
$linkUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_LINK);

$sa = $_objectManager->get('Sahy\Banner\Block\Frontend\Banners');
$banners = $sa->getAllBannerByType($sa::TYPE_HOME_BANNER);
$_sub = $sa->getAllBannerByType($sa::TYPE_SUB_BANNER);
?>

<div id="homePage" class="col-1200">
<!-- Home Banner Slider -->
<?php if (isset($banners) && count($banners) > 0) { ?>
    <?php $size = count($banners); ?>

    <div id="bannerHS" class="carousel slide" data-ride="carousel" data-interval="false">
        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">
            <?php $i = 1; ?>
            <?php foreach ($banners as $bn) { ?>
                <div class="item <?= ($i == 1) ? 'active' : '' ?>">
                    <img src="<?= $mediaUrl . $bn['image'] ?>"/>
                </div>
                <?php $i++; ?>
            <?php } ?>
        </div>
        <!-- Controls -->
        <a class="left carousel-control" href="#bannerHS" role="button" data-slide="prev">
            <div class="prevButtonWrap sliderIcon" aria-hidden="true">
                <img src="<?= $mediaUrl ?>images/icon/left.png"/>
            </div>
        </a>
        <a class="right carousel-control" href="#bannerHS" role="button" data-slide="next">
            <div class="nextButtonWrap sliderIcon" aria-hidden="true">
                <img src="<?= $mediaUrl ?>images/icon/right.png"/>
            </div>
        </a>

        <!-- Indicators -->
        <ol class="carousel-indicators">
            <?php $i = 0 ?>
            <?php foreach ($banners as $bn) { ?>
                <li data-target="#bannerHS" data-slide-to="<?= $i ?>" class="<?= ($i == 0) ? 'active' : '' ?>"></li>
                <?php $i++; ?>
            <?php } ?>
        </ol>
    </div>

<?php } ?>

<!-- Sub Banner  -->
<div class="row subBanner">
    <?php $i = 1; ?>
    <?php foreach ($_sub as $item) { ?>
        <div class="col-xs-4 col-sm-4 subBannerItem">
            <a href="<?= $item['link'] ?>">
                <div class="img-resp img75">
                    <img class="" src="<?= $mediaUrl . $item['image'] ?>"/>
                </div>
            </a>
        </div>
        <?php $i++; ?>
    <?php } ?>
</div>
<div class="clearfix pad30"></div>
<!-- # Sub Banner  -->

<?php // Get Latest Products
$productModel = $_objectManager->get('Magento\Catalog\Model\Product');
$parentProduct = $_objectManager->create('Magento\ConfigurableProduct\Model\ResourceModel\Product\Type\Configurable');
$productCollection = $_objectManager->create('Magento\Catalog\Model\ResourceModel\Product\CollectionFactory');
$collection = $productCollection->create()
    ->addAttributeToSelect('*')
    ->addFieldToFilter("status", "1")
    ->addFieldToFilter("type_id", array('eq' => 'configurable'))
    ->setOrder('created_at', 'DESC')
    ->setPageSize(12)
    ->load();
?>

<?php if (isset($collection) && $collection->getSize() > 0) { ?>
    <!-- New Products -->
    <p class="headHome">New Arrivals</p>
    <div id="newProductHS" class="carousel slide productSlider" data-ride="carousel" data-interval="false">
        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">
            <!-- Items -->
            <?php $i = 1; ?>
            <?php foreach ($collection as $newPro) { ?>
                <?php if ($i % 4 == 1) { ?>
                    <div class="item <?= ($i == 1) ? ' active' : '' ?>">
                    <div class="row">
                <?php } ?>

                <?php
                $parUrl = false;
                $parentId = $parentProduct->getParentIdsByChild($newPro->getId());
                if (isset($parentId[0]) && $parentId[0] > 0) {
                    $pId = $parentId[0];
                    $parUrl = $productModel->load($pId)->getUrlKey();
                    $parUrl = $baseUrl . $parUrl .".html";
                }
                ?>

                <div class="HS-item-Resp">
                    <div class="HS-item-wrap">
                        <a href="<?= ($parUrl) ? $parUrl : $newPro->getProductUrl() ?>">
                            <?php $label = ($newPro->getFinalPrice() < $newPro->getPrice()) ? "isSaleLB ":"" ?>
                            <?php $label = $label . ((time() - strtotime($newPro->getCreatedAt()) < 1209600) ? "isNewLB ":""); ?>
                            <div class="img-resp img133 <?= $label ?>">
                                <img src="<?= $mediaUrl . 'catalog/product' . $newPro->getThumbnail() ?>"/>
                            </div>
                            <p class="titPSlide"><?= $newPro->getName() ?></p>
                            <p class="pricePSlide">
                                <?= "$" . number_format($newPro->getFinalPrice(), 2) ?>
                                <?php if ($newPro->getFinalPrice() < $newPro->getPrice()) { ?>
                                    <span class="oldPrice"><?= "$" . number_format($newPro->getPrice(), 2) ?></span>
                                <?php } ?>
                            </p>
                        </a>
                    </div>
                </div>
                <?php if ($i % 4 == 0 || $i == $collection->getSize()) { ?>
                    </div>
                    </div>
                <?php } ?>
                <?php $i++; ?>
            <?php } ?>
        </div>
        <!-- Controls -->
        <a href="#newProductHS" role="button" data-slide="prev">
            <div class="prevButtonWrap slideCtr" aria-hidden="true">
                <img src="<?= $mediaUrl ?>images/icon/pLeft.png"/>
            </div>
        </a>
        <a href="#newProductHS" role="button" data-slide="next">
            <div class="nextButtonWrap slideCtr" aria-hidden="true">
                <img src="<?= $mediaUrl ?>images/icon/pRight.png"/>
            </div>
        </a>
    </div>
    <div class="clearfix pad100"></div>
<?php } ?>


</div>

<style>
    .page-layout-1column .column.main { display: none }
</style>