<div class="containerPopUpWrap" id="">
    <div class="popUpInnerWrap">
        <a href="javascript:void(0);" id="closeQuickViewAction">( Close )</a>
        <div class="clearfix"></div>
        <div id="dataQuickView">
            <div class="row">
                <div class="col-xs-12 col-sm-6">
                    <div class="leftImg">
                        <img id="imgQuickView" src="#">
                    </div>
                </div>
                <div class="col-xs-12 col-sm-6">
                    <a href="#" id="titQuickView"></a>
                    <p id="skuQuickView"></p>
                    <p id="priceQuickView"></p>
                    <div class="lineQuickView"></div>
                        <p><span class="headQV">SIZE - </span><span class="valHeadQV" id="sizeValueQV"></span></p>
                        <p><span class="headQV">COLOR: - </span><span class="valHeadQV" id="colorValueQV"></span></p>

                    <div class="lineQuickView"></div>
                    <div id="addToCartQuickView">
                        <form data-role="tocart-form" action="" method="post">
                            <input class="productWV" type="hidden" name="product" value="4876">
                            <input class="uencWV" type="hidden" name="" value="">
                            <input class="formKeyWV" name="form_key" type="hidden" value="hMuxuHYp3xzD2B6o">
                            <button type="submit" title="Add to Cart" class="action tocart primary">
                                <span>Add to Cart</span>
                            </button>
                            <a href="#" id="viewDetailId"><div class="viewDetail">View Detail</div></a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>