<?php
$_objectManager = \Magento\Framework\App\ObjectManager::getInstance(); //instance of \Magento\Framework\App\ObjectManager
$storeManager = $_objectManager->get('Magento\Store\Model\StoreManagerInterface');
$currentStore = $storeManager->getStore();
$baseUrl = $currentStore->getBaseUrl();
$mediaUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
$linkUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_LINK);
$target_id = $block->getTargetId();
$target = $block->getTarget();
$label = $block->getLabel();
?>

<div class="topPartner">
    <a href="#" >
        <img src="<?= $mediaUrl ?>/images/home/tap_logo_siva.png" />
    </a>
    <a href="#" >
        <img src="<?= $mediaUrl ?>/images/home/tap_logo_amfm.png" />
    </a>
    <a href="#" >
        <img src="<?= $mediaUrl ?>/images/home/tap_logo_fof.png" />
    </a>
</div>