<?php // echo $this->getItemUrl($newsItem) ?>
<?php $_news = $this->getCollection(); ?>

<div class="clearfix pad40"></div>
<div class="row">
    <div class="col-xs-12 col-sm-8">
    <?php foreach ($_news as $newsItem): ?>
        <div class="detailInner">
            <div class="detailHead">
                <span><?= $newsItem->getTitle() ?></span>
                <div class="dropContent"></div>
            </div>
            <div class="content hidden">
                <div class="clearfix pad20"></div>
                <?= $newsItem->getContent() ?>
            </div>
        </div>
    <?php endforeach; ?>
    </div>

    <div class="col-xs-12 col-sm-4">
        <div class="detailInner">
            <?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('rightFAQ')->toHtml();?>
        </div>
    </div>
</div>


<script type="text/javascript">
    require(['jquery', 'jquery/ui'], function($){
        $(document).ready(function($) {
            $(window).load(function() {
                $('.detailHead').click(function(){
                    if ($(this).find('.dropContent').hasClass('active')) {
                        $(this).parent().find('.content').addClass("hidden");
                        $(this).find('.dropContent').removeClass("active");
                    } else {
                        $(this).parent().parent().find('.content').addClass("hidden");
                        $(this).parent().parent().find('.dropContent').removeClass("active");
                        $(this).parent().find('.content').removeClass("hidden");
                        $(this).find('.dropContent').addClass("active");
                    }
                })
            });
        });
    });
</script>