<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Customer\Block\Account\AuthorizationLink */
$dataPostParam = '';
if ($block->isLoggedIn()) {
    $dataPostParam = sprintf(" data-post='%s'", $block->getPostParams());
}
?>
<li class="authorization-link kong">
    <a <?= $block->getLinkAttributes() . $dataPostParam; ?>>
        <span>
            <img src="/pub/media/images/icon/customer.png" class="customerIcon" />
            <?= $block->escapeHtml($block->getLabel()); ?>
        </span>
    </a>
</li>
