<?php
/**
 * Copyright © 2015 Ihor Vansach (ihor@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog post list item template
 *
 * @var $block \Magefan\Blog\Block\Post\AbstractPost
 */
?>
<?php
    $_post = $this->getPost();
    $_postUrl = $_post->getPostUrl();
    $_postName = $block->escapeHtml($_post->getTitle(), null, true);
?>
<li class="post-holder post-holder-<?= $_post->getId() ?>">
    <div class="post-header">
        <div class="post-title-holder clearfix">
            <h3 class="post-title"><?= $_postName; ?></h3>
            <div class="clickDropBlog" data-id="<?= $_post->getId() ?>"></div>
        </div>

    </div>

    <div class="post-content" style="display: none">
        <div class="clearfix pad20"></div>
        <div class="addthis_toolbox addthis_default_style" addthis:url="<?= $_postUrl ?>">
            <a class="addthis_button_facebook"></a>
            <a class="addthis_button_twitter"></a>
            <a class="addthis_button_email"></a>
            <a class="addthis_button_compact"></a>
        </div>

        <?= $this->getInfoHtml() ?>

        <div class="post-description clearfix">
            <?php if ($featuredImage = $_post->getFeaturedImage()) { ?>
            <div class="post-ftimg-hld">
                <a href="<?= $_postUrl ?>" title="<?= $_postName ?>">
                    <img src="<?= $featuredImage ?>" alt="<?= $_postName ?>" />
                </a>
            </div>
            <?php } ?>
            <div class="post-text-hld clearfix">
                <?= $block->getShorContent() ?>
            </div>

        </div>
    </div>
    <div class="post-footer">

    </div>
</li>